shopping_cart/Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using shopping_cart.Models;

namespace shopping_cart.Controllers
{
    public class OrdersController : Controller
    {
        private ShoppingCartModel db = new ShoppingCartModel();

        // GET: Orders
        public ActionResult Index()
        {
            return View(db.Tbl_Orders.ToList());
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Orders tbl_Orders = db.Tbl_Orders.Find(id);
            if (tbl_Orders == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Orders);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Pk_OrderID,Email")] Tbl_Orders tbl_Orders)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Orders.Add(tbl_Orders);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Orders);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Orders tbl_Orders = db.Tbl_Orders.Find(id);
            if (tbl_Orders == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Orders);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Pk_OrderID,Email")] Tbl_Orders tbl_Orders)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Orders).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Orders);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Orders tbl_Orders = db.Tbl_Orders.Find(id);
            if (tbl_Orders == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Orders);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Orders tbl_Orders = db.Tbl_Orders.Find(id);
            db.Tbl_Orders.Remove(tbl_Orders);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddItem(int id)
        {
            var cart = (Session["Cart"] == null) ? new List<int> { } : (List<int>)Session["Cart"];

            cart.Add(id);

            Session["Cart"] = cart;

            return RedirectToAction("Index", "Products", new { });
        }

        [HttpGet]
        public ActionResult Checkout()
        {
            var cart = (Session["Cart"] == null) ? new List<int> { } : (List<int>)Session["Cart"];

            var cartItems = db.Tbl_Products.Where(x => cart.Contains(x.Pk_ProductID)).ToList();

            var model = new CartViewModel
            {
                SelectedItems = cartItems
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult Checkout(CartViewModel model)
        {
            if (ModelState.IsValid)
            {
                var order = new Tbl_Orders {
                    Email = model.Email
                };

                foreach(var item in model.SelectedItems)
                {
                    var orderItem = new Tbl_OrderProduct
                    {
                        Fk_OrderID = order.Pk_OrderID,
                        Fk_ProductID = item.Pk_ProductID
                    };

                    order.Tbl_OrderProduct.Add(orderItem);
                }

                db.Tbl_Orders.Add(order);
                db.SaveChanges();

                ModelState.Clear();

                Session["Cart"] = null;

                return RedirectToAction("Index", "Products");              
               
            }
            return View(new CartViewModel()); 
        }

        public ActionResult OrderHistory()
        {        
            List<OrderHistoryViewModel> OrderHistoryList = new List<OrderHistoryViewModel>();

            var allOrders = db.Tbl_Orders.ToList();

            foreach(var item in allOrders)
            {
                var order = new OrderHistoryViewModel
                {
                    Id = item.Pk_OrderID,
                    Email = item.Email,
                    OrderItems = item.Tbl_OrderProduct.Select(x => new OrderItemViewModel
                    {
                        Id = x.Pk_OrderProdictID,
                        ProductName = x.Tbl_Products.ProductName
                    }).ToList()
                };

                OrderHistoryList.Add(order);
            }

            return View(OrderHistoryList);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

shopping_cart/Controllers/ProductsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using shopping_cart.Models;

namespace shopping_cart.Controllers
{
    public class ProductsController : Controller
    {
        private ShoppingCartModel db = new ShoppingCartModel();

        // GET: Products
        public ActionResult Index()
        {
            return View(db.Tbl_Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Products tbl_Products = db.Tbl_Products.Find(id);
            if (tbl_Products == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Products);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Pk_ProductID,ProductName,ProductPicture")] Tbl_Products tbl_Products)
        {
            if (ModelState.IsValid)
            {
                db.Tbl_Products.Add(tbl_Products);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Products);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Products tbl_Products = db.Tbl_Products.Find(id);
            if (tbl_Products == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Products);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Pk_ProductID,ProductName,ProductPicture")] Tbl_Products tbl_Products)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Products).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Products);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tbl_Products tbl_Products = db.Tbl_Products.Find(id);
            if (tbl_Products == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tbl_Products tbl_Products = db.Tbl_Products.Find(id);
            db.Tbl_Products.Remove(tbl_Products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

shopping_cart/Views/Products/Create.cshtml
@model shopping_cart.Models.Tbl_Products

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pk_ProductID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pk_ProductID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pk_ProductID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

shopping_cart/Views/Products/Delete.cshtml
@model shopping_cart.Models.Tbl_Products

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tbl_Products</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPicture)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPicture)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

shopping_cart/Views/Products/Details.cshtml
@model shopping_cart.Models.Tbl_Products

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">    
    <hr />
        <div class="col-lg-12 col-sm-12 text-center" style="font-size: large">
            <img src="@Url.Content(Model.ProductPicture)" class="img-responsive img-rounded" style="margin:0 auto" alt="Picture" height="531" width="531" /><br/>
            @Html.ActionLink(Model.ProductName + " - Add to Cart", "AddItem", "Orders", new { id = Model.Pk_ProductID }, null)            
        </div>
</div>

shopping_cart/Views/Products/Edit.cshtml
@model shopping_cart.Models.Tbl_Products

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tbl_Products</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Pk_ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductPicture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductPicture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductPicture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

shopping_cart/Views/Products/Index.cshtml
@model IEnumerable<shopping_cart.Models.Tbl_Products>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br />

@Html.AntiForgeryToken()

<div class="form-actions no-color text-right">

        @*<button type="button" value="Checkout" class="btn btn-default">
            @Html.ActionLink("Create New", "Create")
        </button>*@

    <input type="button" name="Checkout" value="Checkout" onclick="location.href='@Url.Action("Checkout", "Orders")' " class="btn btn-default" />
</div>

<hr />

<div class="container">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-6 col-sm-6 text-center">
                @if (item.Pk_ProductID % 2 != 0)
                {
                    <img src="@Url.Content(@item.ProductPicture)" alt="Picture" class="img-responsive img-rounded" /><br />
                    @Html.ActionLink(item.ProductName, "Details", new { id = item.Pk_ProductID })<br />
                }
            </div>
            <div class="col-md-6 col-sm-6 text-center">
                @if (item.Pk_ProductID % 2 == 0)
                {
                    <img src="@Url.Content(@item.ProductPicture)" alt="Picture" class="img-responsive img-rounded" /><br />
                    @Html.ActionLink(item.ProductName, "Details", new { id = item.Pk_ProductID })<br />
                }
            </div>
        }
    </div>
</div>